/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc721Sol from "./MyERC721.sol";
export { MyERC20__factory } from "./MyERC20__factory";
export { MyToken__factory } from "./MyToken__factory";
