/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErc721Sol from "./MyERC721.sol";
export type { myErc721Sol };
export type { MyERC20 } from "./MyERC20";
export type { MyToken } from "./MyToken";
